server:
  port: 22345

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.fakedomain: debug
    com.baomidou.mybatisplus.core.executor.BaseExecutor: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus_native_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: mybatis_plus_native_demo
    password: x_q3WjlZ7t_1JjHv
